### ISSUE TITLE
[D3FC] Clipping x-axis labels

### ISSUE THREAD

**Issue by neilslinger** [jpmorganchase/perspective#500]
When plotting crowded x-axis, the angle of the text is altered to attempt to better fit the text. However, its possible to get the text to clip as shown here (left-hand-side):

![image](https://user-images.githubusercontent.com/2312834/55009334-44f6ca80-4fda-11e9-94d7-f1b24af88b80.png)

**Comment by DevAndyLee** [comment]
What is the preferred solution?

Is it to hide the labels that are getting clipped? There are a lot of labels that have been hidden in the above example anyway, so that seems sensible, and quite easy to implement.

Or else, is it to increase the left margin to make space available? This would be somewhat harder, as the idea of dynamically sizing the grid isn't well supported by D3FC (yet).

Presumably, at some point, we'll need to limit the maximum text length shown in labels as well? e.g. it they are too long, the labels will take up the whole screen and leave no room for the chart. In that case, what would the limit be?

**Comment by DevAndyLee** [comment]
I've gone for the first option, which should be included in the next PR.

**Comment by texodus** [comment]
This was fixed in 0.2.23!  Thanks!
